apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dgb-volume-claim-{{ .Release.Name }}
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
