{{- if .Values.global.ingress.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: digibyte-node-ingress-rpc-{{ .Release.Name }}
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  entryPoints:
    - digibyte-rpc
  routes:
    - match: HostSNI(`*`)
      services:
        - name: rpc-digibyte-node-{{ .Release.Name }}
          port: 14022
{{- end }}
