apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mattermost.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mattermost.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "mattermost.chart" . }}
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: null
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mattermost.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret-config.yaml") . | sha256sum }}
        {{- if .Values.extraPodAnnotations }}
        {{- .Values.extraPodAnnotations | toYaml | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "mattermost.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ include "mattermost.chart" . }}
    spec:
      initContainers:
      {{- if not .Values.externalDB.enabled }}
      - name: "init-mysql"
        image: "{{ .Values.initContainerImage.repository }}:{{ .Values.initContainerImage.tag }}"
        imagePullPolicy: {{ .Values.initContainerImage.imagePullPolicy }}
        command: ["sh", "-c", "until curl --max-time 10 http://{{ .Release.Name }}-mysql:3306; do echo waiting for {{ .Release.Name }}-mysql; sleep 5; done;"]
      {{- end }}
      {{- if .Values.extraInitContainers }}
      {{- .Values.extraInitContainers | toYaml | nindent 6 }}
      {{- end }}
      - name: copy-config
        image: "alpine:latest"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /mattermost/config/config.json
          name: config-json
          subPath: config.json
        - mountPath: /mattermost/data
          name: mattermost-data
        command: ["/bin/ash", "-c", "if [ ! -f /mattermost/data/config.json ]; then cp -fp /mattermost/config/config.json /mattermost/data/config.json && chmod -R 777 /mattermost/data;fi"]
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        env:
        {{- if .Values.extraEnvVars }}
          {{- .Values.extraEnvVars | toYaml | nindent 10 }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 90
          timeoutSeconds: 5
          periodSeconds: 15
          httpGet:
            path: /api/v4/system/ping
            port: http
        readinessProbe:
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 15
          httpGet:
            path: /api/v4/system/ping
            port: http
        volumeMounts:
        - mountPath: /mattermost/config/config.json
          name: config-json
          subPath: config.json

        - mountPath: /mattermost/data
          name: mattermost-data
        - mountPath: /mattermost/{{ trimPrefix "./" .Values.configJSON.PluginSettings.Directory }}
          name: mattermost-plugins
        {{- if .Values.extraVolumeMounts -}}
        {{ .Values.extraVolumeMounts | toYaml | nindent 8 }}
        {{- end }}
        resources:
          {{- .Values.resources | toYaml | nindent 12 }}
      volumes:
      {{- if .Values.extraVolumes -}}
      {{ .Values.extraVolumes | toYaml | nindent 6 }}
      {{- end }}
      - name: config-json
        secret:
          secretName: {{ include "mattermost.fullname" . }}-config-json
      - name: mattermost-data
      # {{ if .Values.persistence.data.enabled }}
        persistentVolumeClaim:
          claimName: {{ default (include "mattermost.fullname" .) }}-data-claim
      # {{ else }}
        # emptyDir: {}
      # {{ end }}
      - name: mattermost-plugins
      {{ if .Values.persistence.plugins.enabled }}
        persistentVolumeClaim:
          {{ if .Values.persistence.plugins.existingClaim }}
          claimName: {{.Values.persistence.plugins.existingClaim }}
          {{ else }}
          claimName: {{ default (include "mattermost.fullname" .) }}-plugins
          {{ end }}
      {{ else }}
        emptyDir: {}
      {{ end }}
