apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: taiga-ingress
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
    backupType: {{ .Values.threefoldVdc.backup | quote }}
  annotations:
  {{- if .Values.global.ingress.certresolver }}
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.global.ingress.certresolver }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: taiga-service
            servicePort: 80
