apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hmy-volume-claim
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
