kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  {{ include "zeroci.fullname" . }}
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  {{ include "zeroci.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "zeroci.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name:   {{ include "zeroci.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
