apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: taiga-ingress
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
    backupType: {{ .Values.threefoldVdc.backup | quote }}
{{- with .Values.ingress.annotations }}
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.global.ingress.certresolver }}
{{ toYaml . | nindent 4 }}
{{- end }}
    
spec:
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ index .Values "services" "taiga-gateway" "name" }}
          servicePort: {{ index .Values "services" "taiga-gateway" "port" }}