apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: taiga
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/taiga: "true"
  podSelector:
    matchLabels:
      io.kompose.network/taiga: "true"
