{{- if .Values.resources -}}
apiVersion: v1
kind: LimitRange
metadata:
  name: taiga-limit-range
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  limits:
  - max:
      cpu: "{{ div (sub .Values.resources.cpu 300) 6 }}m"
      memory: "{{ div (sub .Values.resources.memory 300) 6 }}Mi"
    defaultRequest:
      cpu: "{{ div .Values.resources.cpu 10 }}m"
      memory: "{{ div .Values.resources.memory 10 }}Mi"
    type: Container

# PODS RESOURCES:

# Const Resources:
#                     cpu mem
# taiga-gateway:      100 100
# taiga-front:        100 100
# taiga-protected:    100 100
# ----------------------------
#                     300 300

# the rest is divided equally on these 6 pods
# taiga-async,
# taiga-async-rabbitmq,
# taiga-events,
# taiga-events-rabbitmq,
# taiga-back,
# taiga-db
{{- end }}