apiVersion: v1
kind: Secret
metadata:
  name: taiga-back-secret-key
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
type: Opaque
stringData:
  secret: {{ .Values.backendSecretKey }}

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-erlang-cookie
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
type: Opaque
stringData:
  secret: {{ .Values.rabbitmq.rabbitmqErlangCookie }}

---
apiVersion: v1
kind: Secret
metadata:
  name: api-app-secret-key
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
type: Opaque
stringData:
  secret: {{ .Values.threefoldlogin.apiAppSecret }}

---
{{- if .Values.emailSettings.emailEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: email-smtp-password
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
type: Opaque
stringData:
  secret: {{ .Values.emailSettings.emailSmtpPassword }}
{{- end }}
