apiVersion: v1
kind: Secret
metadata:
  name: taiga-back-secret-key
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
type: Opaque
stringData:
  secret: {{ .Values.backendSecretKey }}

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-erlang-cookie
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
type: Opaque
stringData:
  secret: {{ .Values.rabbitmq.rabbitmqErlangCookie }}
