apiVersion: v1
kind: Service
metadata:
  name: taiga-service
  labels:
    backupType: {{ .Values.threefoldVdc.backup }}
spec:
  selector:
    {{- include "taiga.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
