{{- if .Values.ingress.enabled -}}
{{- $fullName := include "mastodon.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.global.ingress.certresolver }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: '/'
            backend:
              serviceName: {{ $fullName }}-web
              servicePort: {{ $svcPort }}
          - path: '/api/v1/streaming'
            backend:
              serviceName: {{ $fullName }}-streaming
              servicePort: {{ .Values.application.streaming.port }}
{{- end }}
