apiVersion: v1
kind: ResourceQuota
metadata:
  name: mastodon-resource-quota
spec:
  hard:
    limits.cpu: "{{ .Values.resources.limits.cpu }}m"
    limits.memory: "{{ .Values.resources.limits.memory }}Mi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mastodon-limit-range
spec:
  limits:
  - default:
      cpu: "{{ div  (sub .Values.resources.limits.cpu (div .Values.resources.limits.cpu 3))  6 }}m"
      memory: "{{ div (sub .Values.resources.limits.memory (div .Values.resources.limits.memory 3)) 6 }}Mi"
    defaultRequest:
      cpu: "265m"
      memory: "100Mi"
    type: Container

# PODS RESOURCES:

# Const Resources:
#                     cpu       mem
# web:                cpu/3     mem/3

# the rest is divided equally on these 6 pods
# streaming,
# sidekiq,
# redis,
# postgres,
# metrics,
# post-install
