apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mastodon.fullname" . }}
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY_BASE: "{{ .Values.secrets.secret_key_base | b64enc }}"
  OTP_SECRET: "{{ .Values.secrets.otp_secret | b64enc }}"
  VAPID_PRIVATE_KEY: "{{ .Values.secrets.vapid.private_key | b64enc }}"
  VAPID_PUBLIC_KEY: "{{ .Values.secrets.vapid.public_key | b64enc }}"
