apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubeapps.apprepository-jobs-cleanup.fullname" . }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "-10"
  labels:
    {{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    backupType: {{ .Values.threefoldVdc.backup | quote }}
    app: {{ template "kubeapps.apprepository-jobs-cleanup.fullname" . }}
