apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubeapps.kubeops.fullname" . }}
  labels:
    {{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    backupType: {{ .Values.threefoldVdc.backup | quote }}
    app: {{ template "kubeapps.kubeops.fullname" . }}
