apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubeapps.kubeops.fullname" . }}
  labels:
    {{ include "kubeapps.labels" . | nindent 4 }}
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.kubeops.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "kubeapps.kubeops.fullname" . }}
    release: {{ .Release.Name }}
