apiVersion: v1
kind: Service
metadata:
  name: web-presearch-node-{{ .Release.Name }}
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
    {{- include "presearch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    {{- include "presearch.selectorLabels" . | nindent 4 }}
