apiVersion: v1
kind: PersistentVolume
metadata:
  name: dash-volume
  labels:
    type: local
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  storageClassName: local-path
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dash"
