apiVersion: v1
kind: Service
metadata:
  name: p2p-dash-node
  labels:
    {{- include "dash.labels" . | nindent 4 }}
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9998
      targetPort: 9998
  selector:
    {{- include "dash.selectorLabels" . | nindent 4 }}
