apiVersion: v1
kind: LimitRange
metadata:
  name: {{ template "peertube.fullName" . }}
  labels:
    {{- include "peertube.labels" . | nindent 4 }}
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  limits:
  - default:
      cpu: "250m"
      memory: "256Mi"
    type: Container