{{- if and .Values.prometheus.enabled .Values.rbac.create .Values.rbac.pspEnabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kube-prometheus.prometheus.fullname" . }}-psp
  labels: 
    {{- include "kube-prometheus.prometheus.labels" . | nindent 4 }}
    backupType: {{ .Values.threefoldVdc.backup | quote }}
rules:
  - apiGroups: ['extensions']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames:
      - {{ template "kube-prometheus.prometheus.fullname" . }}
{{- end }}
