{{- if .Values.ingress.enabled -}}
{{- $fullName := include "publishingtools.fullname" . -}}
{{ if eq .Values.env.type "blog" }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-app-root
  namespace: default
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  redirectRegex:
    regex: ^https://{{ .Values.ingress.host }}/$
    replacement: https://{{ .Values.ingress.host }}/blog/site
{{ else }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-request-modifier
  namespace: default
spec:
  addPrefix:
    prefix: /site
{{ end }}
---
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "publishingtools.labels" . | nindent 4 }}
  annotations:
    # change app-root or modify request according to type (blog or website/wiki)
    {{ if eq .Values.env.type "blog" }}
    traefik.ingress.kubernetes.io/router.middlewares: default-{{ $fullName }}-app-root@kubernetescrd
    {{ else }}
    traefik.ingress.kubernetes.io/router.middlewares: default-{{ $fullName }}-request-modifier@kubernetescrd
    {{ end }}
    {{- if .Values.global.ingress.certresolver }}
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.global.ingress.certresolver }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
        {{- range .Values.ingress.paths }}
        - path: {{ . }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $svcPort }}
        {{- end }}
  {{- end }}
