apiVersion: v1
kind: Service
metadata:
  name: {{ include "publishingtools.fullname" . }}
  labels:
    {{- include "publishingtools.labels" . | nindent 4 }}
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "publishingtools.selectorLabels" . | nindent 4 }}
