{{- if .Values.global.ingress.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: dash-ingrpc-{{ .Release.Name }}
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  entryPoints:
    - dash-rpc
  routes:
    - match: HostSNI(`*`)
      services:
        - name: rpc-{{ .Release.Name }}
          port: 9998
{{- end }}
