{{- if .Values.global.ingress.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: dash-ingp2p-{{ .Release.Name }}
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  entryPoints:
    - dash-p2p
  routes:
    - match: HostSNI(`*`)
      services:
        - name: p2p-{{ .Release.Name }}
          port: 9999
{{- end }}
