apiVersion: v1
kind: Service
metadata:
  name: p2p-dash-node-{{ .Release.Name }}
  labels:
    {{- include "dash.labels" . | nindent 4 }}
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 12024
      targetPort: 12024
  selector:
    {{- include "dash.selectorLabels" . | nindent 4 }}
