apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ include "minio.fullname" . }}-minio"
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  capacity:
    storage: "{{ .Values.volume.size }}Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  hostPath:
    path: {{ .Values.volume.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "minio.fullname" . }}-pv-claim
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.volume.size }}Gi"
  storageClassName: ""
  volumeName: "{{ include "minio.fullname" . }}-minio"

