{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "3bot.serviceAccountName" . }}
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
    {{- include "3bot.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
