apiVersion: v1
kind: Service
metadata:
  name: bor-{{ .Release.Name }}
  labels:
    {{- include "matic.labels" . | nindent 4 }}
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 30303
      targetPort: 30303
  selector:
    {{- include "matic.selectorLabels" . | nindent 4 }}
