apiVersion: v1
kind: Secret
metadata:
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
  name: {{ .Release.Name }}-auth
data:
  access_code: {{ .Values.access_code | quote | b64enc }}
