apiVersion: v1
kind: Service
metadata:
  name: web{{ .Release.Name }}
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
    {{- include "matic.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    {{- include "matic.selectorLabels" . | nindent 4 }}
